## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 0.6
  - 0.7
notifications:
  email: false
git:
  depth: 99999999

# Integration with JuMP-dev gitter channel
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb052648b833828852b4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

## uncomment the following lines to override the default test script
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MathOptInterface"); Pkg.add("Compat")' # warnings here about needed to do using Pkg but it also installs Compat
  # TODO: re-enable depwarn=error after https://github.com/JuliaLang/Compat.jl/pull/602 is tagged.
  #- julia --depwarn=error -e 'using Compat; using Compat.Pkg; Pkg.test("MathOptInterface"; coverage=true)'
  - julia -e 'using Compat; using Compat.Pkg; Pkg.test("MathOptInterface"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("MathOptInterface")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MathOptInterface")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("MathOptInterface")); include(joinpath("docs", "make.jl"))'
